name: ipyflex
channels:
  - conda-forge
dependencies:
  - jupyterlab=3
  - bqplot
  - numpy
  - ipywidgets
  - ipyvuetify
  - plotly
  - ipygany
  - bqplot
  - ipydatagrid 
  - yfinance
  - nodejs
  - yarn
