name: ipyflex
channels:
  - conda-forge
dependencies:
  - jupyterlab=4
  - bqplot
  - numpy
  - ipywidgets
  - ipyvuetify
  - plotly
  - ipygany
  - bqplot
  - ipydatagrid
  - yfinance
  - nodejs
  - jlpm
