name: Build

on:
  push:
    branches: master
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Setup pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: pip-3.9-${{ hashFiles('package.json') }}
          restore-keys: |
            pip-3.9-
            pip-

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          python -m pip install -U pip flake8

      - name: Test the extension
        run: |
          python -m pip install --upgrade -v -e ".[test, docs]"
          jlpm run lint:check
          python -m flake8 ipyflex
          pytest

      - name: Package the extension
        run: |
          pip install build
          python -m build
          pip uninstall -y "ipyflex" jupyterlab

      # - name: Check docs can be build + links
      #   run: |
      #     sudo apt install -y pandoc
      #     pushd docs
      #     make html
      #     python -m pytest --check-links
      #     popd
